### ISSUE TITLE
overflow due to dim resize using CByte instead of CInt

### ISSUE THREAD

**Issue by PerditionC** [EagleAglow/vba-websocket-class#1]
I am attempting to use this class in a VBA project to talk to Chrome/Edge via CDP and discovered that upon receiving a message larger than 256 bytes an error is thrown.  In cWebSocket.cls function GetMessageUTF8, 2nd to last line, the redim is attempting to convert the receive size to a byte which can cause an Overflow error to be thrown.  I believe this should be using CInt as the buffer itself is more than 256 bytes. 

https://github.com/EagleAglow/vba-websocket-class/blob/c1447345287abee39a852f912ac2930edaf969c6/CWebSocket.cls#L554

I.e change
ReDim Preserve rgbBuffer(**CByte**(dwBytesTransferred))
to
ReDim Preserve rgbBuffer(**CInt**(dwBytesTransferred))

Thank you.

**Comment by EagleAglow** [comment]
Changed. Also fixed similar line for rgbOther variable

**Comment by PerditionC** [comment]
Thank you.

**Comment by EagleAglow** [comment]
You're welcome!  Also fixed the server, issue #2.  I hope you find this thing useful, but be prepared to be disappointed.  I'm not sure VBA is actually capable of making asynchronous websockets reliable.  Also, my VBA class writing is a bit iffy. 😊
