### ISSUE TITLE
echo.websocket.org was shutdown

### ISSUE THREAD

**Issue by PerditionC** [EagleAglow/vba-websocket-class#2]
https://github.com/EagleAglow/vba-websocket-class/blob/c1447345287abee39a852f912ac2930edaf969c6/Main.bas#L26

As echo.websocket.org was shutdown it may be worthwhile to change to another example echo server such as echo.websocket.events as mentioned here https://www.lob.com/blog/websocket-org-is-down-here-is-an-alternative

**Comment by EagleAglow** [comment]
Excellent suggestion! Implemented...
